apiVersion: v1
kind: Service
metadata:
  name: deepspeed-test-0
  namespace: default
  labels:
    app: deepspeed-test-0
spec:
  clusterIP: None
  ports:
  - name: ssh-port
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: deepspeed-test-0
  type: ClusterIP
