---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-data-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.12.16.41
    path: /data/nfsshare/zengzhiyong
    readOnly: false
  persistentVolumeReclaimPolicy: Retain


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: training-data
  namespace: default   
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: training-data-pv
